import type { Student } from "../types";

export const mockStudents: Student[] = [
  {
    id: 1,
    mssv: "SV001",
    hoTen: "Nguyễn Văn A",
    gmail: "nguyenvana@student.niiu.edu.vn",
    khoa: "Công nghệ thông tin",
    khoaHoc: "2020",
    lop: "CNTT-20A",
    soDienThoai: "0901234567",
    deTai: "Xây dựng hệ thống quản lý đồ án",
    giangVienHuongDan: "TS. Trần Văn B",
    trangThai: "active",
    ngaySinh: "2002-01-15",
    diaChi: "TP. Hồ Chí Minh",
  },
  {
    id: 2,
    mssv: "SV002",
    hoTen: "Trần Thị B",
    gmail: "tranthib@student.niiu.edu.vn",
    khoa: "Công nghệ thông tin",
    khoaHoc: "2020",
    lop: "CNTT-20A",
    soDienThoai: "0902345678",
    trangThai: "active",
    ngaySinh: "2002-03-20",
    diaChi: "Hà Nội",
  },
  {
    id: 3,
    mssv: "SV003",
    hoTen: "Lê Văn C",
    gmail: "levanc@student.niiu.edu.vn",
    khoa: "Khoa học máy tính",
    khoaHoc: "2021",
    lop: "KHDL-21A",
    soDienThoai: "0903456789",
    deTai: "Nghiên cứu AI trong y tế",
    giangVienHuongDan: "PGS. Hoàng Thị D",
    trangThai: "active",
    ngaySinh: "2003-05-10",
    diaChi: "Đà Nẵng",
  },
  {
    id: 4,
    mssv: "SV004",
    hoTen: "Phạm Thị E",
    gmail: "phamthie@student.niiu.edu.vn",
    khoa: "Khoa học máy tính",
    khoaHoc: "2021",
    lop: "KHDL-21B",
    soDienThoai: "0904567890",
    trangThai: "active",
    ngaySinh: "2003-08-25",
    diaChi: "Cần Thơ",
  },
  {
    id: 5,
    mssv: "SV005",
    hoTen: "Hoàng Văn F",
    gmail: "hoangvanf@student.niiu.edu.vn",
    khoa: "Kỹ thuật phần mềm",
    khoaHoc: "2020",
    lop: "KTPM-20A",
    soDienThoai: "0905678901",
    deTai: "Phát triển ứng dụng di động",
    giangVienHuongDan: "TS. Nguyễn Văn G",
    trangThai: "active",
    ngaySinh: "2002-11-30",
    diaChi: "Hải Phòng",
  },
  {
    id: 6,
    mssv: "SV006",
    hoTen: "Đặng Thị H",
    gmail: "dangthih@student.niiu.edu.vn",
    khoa: "An toàn thông tin",
    khoaHoc: "2022",
    lop: "ATTT-22A",
    soDienThoai: "0906789012",
    trangThai: "active",
    ngaySinh: "2004-02-14",
    diaChi: "Quảng Ninh",
  },
  {
    id: 7,
    mssv: "SV007",
    hoTen: "Bùi Văn I",
    gmail: "buivani@student.niiu.edu.vn",
    khoa: "Công nghệ thông tin",
    khoaHoc: "2020",
    lop: "CNTT-20B",
    soDienThoai: "0907890123",
    deTai: "Hệ thống IoT thông minh",
    giangVienHuongDan: "TS. Lê Thị J",
    trangThai: "active",
    ngaySinh: "2002-06-18",
    diaChi: "Vũng Tàu",
  },
  {
    id: 8,
    mssv: "SV008",
    hoTen: "Ngô Thị K",
    gmail: "ngothik@student.niiu.edu.vn",
    khoa: "Khoa học dữ liệu",
    khoaHoc: "2021",
    lop: "KHDL-21A",
    soDienThoai: "0908901234",
    trangThai: "active",
    ngaySinh: "2003-09-22",
    diaChi: "Biên Hòa",
  },
  {
    id: 9,
    mssv: "SV009",
    hoTen: "Đỗ Văn L",
    gmail: "dovanl@student.niiu.edu.vn",
    khoa: "Kỹ thuật phần mềm",
    khoaHoc: "2020",
    lop: "KTPM-20B",
    soDienThoai: "0909012345",
    deTai: "Ứng dụng Blockchain",
    giangVienHuongDan: "PGS. Vũ Văn M",
    trangThai: "active",
    ngaySinh: "2002-12-05",
    diaChi: "Thanh Hóa",
  },
  {
    id: 10,
    mssv: "SV010",
    hoTen: "Trịnh Thị N",
    gmail: "trinhthin@student.niiu.edu.vn",
    khoa: "An toàn thông tin",
    khoaHoc: "2022",
    lop: "ATTT-22A",
    soDienThoai: "0910123456",
    trangThai: "graduated",
    ngaySinh: "2004-04-28",
    diaChi: "Nghệ An",
  },
];
