// ============================================================
// MENU CONSTANTS — Sidebar navigation items
// ============================================================
import type { Role } from "@/core/permissions/types";

// ---------- Menu Item Types ----------
export interface MenuItem {
  key: string;
  label: string;
  icon?: string; // bootstrap icon class (e.g., "bi bi-house")
  path?: string;
  children?: MenuItem[];
  roles?: Role[];
  permission?: {
    action: string;
    resource: string;
  };
}

export interface MenuSection {
  section: string;
  items: MenuItem[];
}

// ---------- Icon helper (Bootstrap Icons) ----------
export const Icon = {
  house: "bi-house",
  houseFill: "bi-house-fill",
  personCircle: "bi-person-circle",
  person: "bi-person",
  people: "bi-people",
  briefcase: "bi-briefcase",
  award: "bi-award",
  fileText: "bi-file-text",
  fileEarmark: "bi-file-earmark-text",
  folder: "bi-folder",
  folder2open: "bi-folder2-open",
  chartLine: "bi-chart-line",
  barChart: "bi-bar-chart",
  pieChart: "bi-pie-chart",
  bell: "bi-bell",
  bellFill: "bi-bell-fill",
  envelope: "bi-envelope",
  gear: "bi-gear",
  lock: "bi-lock",
  unlock: "bi-unlock",
  shieldLock: "bi-shield-lock",
  shieldCheck: "bi-shield-check",
  bookmarkStar: "bi-bookmark-star",
  trash: "bi-trash",
  pen: "bi-pen",
  plusCircle: "bi-plus-circle",
  dashCircle: "bi-dash-circle",
  xCircle: "bi-x-circle",
  checkCircle: "bi-check-circle",
  exclamationCircle: "bi-exclamation-circle",
  questionCircle: "bi-question-circle",
  info: "bi-info-circle",
  clipboard: "bi-clipboard",
  clipboardCheck: "bi-clipboard-check",
  calendar: "bi-calendar",
  calendarEvent: "bi-calendar-event",
  calendarCheck: "bi-calendar-check",
  clock: "bi-clock",
  clockHistory: "bi-clock-history",
  doorClosed: "bi-door-closed",
  doorOpen: "bi-door-open",
  boxArrowRight: "bi-box-arrow-right",
  boxArrowInRight: "bi-box-arrow-in-right",
  boxArrowInLeft: "bi-box-arrow-in-left",
  arrowLeftRight: "bi-arrow-left-right",
  arrowRightCircle: "bi-arrow-right-circle",
  chevronDown: "bi-chevron-down",
  chevronUp: "bi-chevron-up",
  chevronLeft: "bi-chevron-left",
  chevronRight: "bi-chevron-right",
  grid: "bi-grid",
  list: "bi-list",
  listTask: "bi-list-task",
  layoutSidebar: "bi-layout-sidebar",
  mortarboard: "bi-mortarboard",
  graduationCap: "bi-mortarboard",
  building: "bi-building",
  buildingGear: "bi-building-gear",
  bank: "bi-bank",
  journal: "bi-journal",
  journalArrowUp: "bi-journal-arrow-up",
  personBadge: "bi-person-badge",
  idCard: "bi-id-card",
  send: "bi-send",
  eye: "bi-eye",
  eyeSlash: "bi-eye-slash",
  star: "bi-star",
  starFill: "bi-star-fill",
  heart: "bi-heart",
  heartFill: "bi-heart-fill",
  bookmark: "bi-bookmark",
  bookmarkFill: "bi-bookmark-fill",
  tags: "bi-tags",
  tag: "bi-tag",
  flag: "bi-flag",
  flagFill: "bi-flag-fill",
  megaphone: "bi-megaphone",
  loudpeaker: "bi-loudspeaker",
  download: "bi-download",
  upload: "bi-upload",
  paperclip: "bi-paperclip",
  link45deg: "bi-link-45deg",
  link: "bi-link",
  codeSlash: "bi-code-slash",
  terminal: "bi-terminal",
  cpu: "bi-cpu",
  server: "bi-server",
  router: "bi-router",
  wifi: "bi-wifi",
  globe: "bi-globe",
  globeAmericas: "bi-globe-americas",
  wrench: "bi-wrench",
  tools: "bi-tools",
  shield: "bi-shield",
  shieldPlus: "bi-shield-plus",
  exclamationTriangle: "bi-exclamation-triangle",
  xOctagon: "bi-x-octagon",
  check2All: "bi-check2-all",
  chatLeftText: "bi-chat-left-text",
  clipboardData: "bi-clipboard-data",
  collection: "bi-collection",
  diagram3: "bi-diagram-3",
  funnel: "bi-funnel",
  funnelLeft: "bi-funnel-left",
  sortDown: "bi-sort-down",
  sortUp: "bi-sort-up",
  filter: "bi-filter",
  search: "bi-search",
  zoomIn: "bi-zoom-in",
  zoomOut: "bi-zoom-out",
  fullscreen: "bi-fullscreen",
  fullscreenExit: "bi-fullscreen-exit",
  threeDots: "bi-three-dots",
  threeDotsVertical: "bi-three-dots-vertical",
  arrowUpCircle: "bi-arrow-up-circle",
  arrowDownCircle: "bi-arrow-down-circle",
  plusLg: "bi-plus-lg",
  dashLg: "bi-dash-lg",
  xLg: "bi-x-lg",
  checkLg: "bi-check-lg",
  arrowLeftLg: "bi-arrow-left-lg",
  arrowRightLg: "bi-arrow-right-lg",
  arrowUp: "bi-arrow-up",
  arrowDown: "bi-arrow-down",
  arrowLeft: "bi-arrow-left",
  arrowRight: "bi-arrow-right",
  caretDown: "bi-caret-down",
  caretUp: "bi-caret-up",
  caretLeft: "bi-caret-left",
  caretRight: "bi-caret-right",
  caretDownFill: "bi-caret-down-fill",
  caretUpFill: "bi-caret-up-fill",
} as const;

// ---------- Menu Items ----------
export const MENU_ITEMS: MenuItem[] = [
  {
    key: "dashboard",
    label: "Tổng quan",
    icon: Icon.houseFill,
    path: "/dashboard",
    roles: ["admin", "secretary", "teacher", "student"],
  },
  {
    key: "thesis",
    label: "Đồ án & Đề tài",
    icon: Icon.mortarboard,
    path: "/thesis",
    roles: ["admin", "secretary", "teacher", "student"],
    permission: { action: "read", resource: "thesis" },
  },
  {
    key: "submission",
    label: "Nộp bài",
    icon: Icon.upload,
    path: "/thesis/submission",
    roles: ["student"],
    permission: { action: "read", resource: "thesis_submission" },
  },
  {
    key: "review",
    label: "Phản biện",
    icon: Icon.chatLeftText,
    path: "/thesis/review",
    roles: ["admin", "secretary", "teacher"],
    permission: { action: "read", resource: "thesis_review" },
  },
  {
    key: "score",
    label: "Chấm điểm",
    icon: Icon.clipboardData,
    path: "/thesis/score",
    roles: ["admin", "secretary", "teacher"],
    permission: { action: "read", resource: "thesis_score" },
  },
  {
    key: "defense",
    label: "Bảo vệ",
    icon: Icon.shieldCheck,
    path: "/thesis/defense",
    roles: ["admin", "secretary", "teacher", "student"],
    permission: { action: "read", resource: "thesis_defense" },
  },
  {
    key: "templates",
    label: "Biểu mẫu",
    icon: Icon.fileText,
    path: "/templates",
    roles: ["admin", "secretary", "teacher", "student"],
  },
  {
    key: "student",
    label: "Sinh viên",
    icon: Icon.personBadge,
    path: "/students",
    roles: ["admin", "secretary"],
    permission: { action: "read", resource: "student" },
  },
  {
    key: "department",
    label: "Khoa",
    icon: Icon.building,
    path: "/department",
    roles: ["admin", "secretary"],
    permission: { action: "read", resource: "department" },
  },
  {
    key: "major",
    label: "Ngành",
    icon: Icon.journal,
    path: "/major",
    roles: ["admin", "secretary"],
    permission: { action: "read", resource: "major" },
  },
  {
    key: "class",
    label: "Lớp học",
    icon: Icon.people,
    path: "/class",
    roles: ["admin", "secretary", "teacher"],
    permission: { action: "read", resource: "class" },
  },
  {
    key: "course",
    label: "Học phần",
    icon: Icon.journal,
    path: "/course",
    roles: ["admin", "secretary"],
    permission: { action: "read", resource: "course" },
  },
  {
    key: "user",
    label: "Người dùng",
    icon: Icon.people,
    path: "/user",
    roles: ["admin"],
    permission: { action: "read", resource: "user" },
  },
  {
    key: "role",
    label: "Vai trò",
    icon: Icon.shieldLock,
    path: "/role",
    roles: ["admin"],
    permission: { action: "read", resource: "role" },
  },
  {
    key: "manage-templates",
    label: "Quản lý biểu mẫu",
    icon: Icon.fileText,
    path: "/admin/templates",
    roles: ["admin"],
  },
  {
    key: "announcement",
    label: "Thông báo",
    icon: Icon.megaphone,
    path: "/announcement",
    roles: ["admin", "secretary", "teacher", "student"],
    permission: { action: "read", resource: "announcement" },
  },
  {
    key: "document",
    label: "Tài liệu",
    icon: Icon.folder2open,
    path: "/document",
    roles: ["admin", "secretary", "teacher", "student"],
    permission: { action: "read", resource: "document" },
  },
  {
    key: "report",
    label: "Báo cáo",
    icon: Icon.barChart,
    path: "/report",
    roles: ["admin", "secretary", "teacher"],
    permission: { action: "read", resource: "report" },
  },
  {
    key: "statistic",
    label: "Thống kê",
    icon: Icon.pieChart,
    path: "/statistic",
    roles: ["admin", "secretary"],
    permission: { action: "read", resource: "statistic" },
  },
  {
    key: "audit",
    label: "Nhật ký hệ thống",
    icon: Icon.clockHistory,
    path: "/audit",
    roles: ["admin"],
    permission: { action: "read", resource: "audit_log" },
  },
  {
    key: "setting",
    label: "Cài đặt",
    icon: Icon.gear,
    path: "/setting",
    roles: ["admin"],
    permission: { action: "read", resource: "setting" },
  },
];

// ---------- Menu Sections ----------
export const MENU_SECTIONS: MenuSection[] = [
  {
    section: "Tổng quan",
    items: [
      {
        key: "dashboard",
        label: "Tổng quan",
        icon: Icon.houseFill,
        path: "/dashboard",
        roles: ["admin", "secretary", "teacher", "student"],
      },
      {
        key: "announcement",
        label: "Thông báo",
        icon: Icon.megaphone,
        path: "/announcement",
        roles: ["admin", "secretary", "teacher", "student"],
        permission: { action: "read", resource: "announcement" },
      },
    ],
  },
  {
    section: "Quản lý đồ án",
    items: [
      {
        key: "thesis",
        label: "Đồ án & Đề tài",
        icon: Icon.mortarboard,
        path: "/thesis",
        roles: ["admin", "secretary", "teacher", "student"],
        permission: { action: "read", resource: "thesis" },
      },
      {
        key: "submission",
        label: "Nộp bài",
        icon: Icon.upload,
        path: "/thesis/submission",
        roles: ["student"],
        permission: { action: "read", resource: "thesis_submission" },
      },
      {
        key: "review",
        label: "Phản biện",
        icon: Icon.chatLeftText,
        path: "/thesis/review",
        roles: ["admin", "secretary", "teacher"],
        permission: { action: "read", resource: "thesis_review" },
      },
      {
        key: "score",
        label: "Chấm điểm",
        icon: Icon.clipboardData,
        path: "/thesis/score",
        roles: ["admin", "secretary", "teacher"],
        permission: { action: "read", resource: "thesis_score" },
      },
      {
        key: "defense",
        label: "Bảo vệ",
        icon: Icon.shieldCheck,
        path: "/thesis/defense",
        roles: ["admin", "secretary", "teacher", "student"],
        permission: { action: "read", resource: "thesis_defense" },
      },
      {
        key: "templates",
        label: "Biểu mẫu",
        icon: Icon.fileText,
        path: "/templates",
        roles: ["admin", "secretary", "teacher", "student"],
      },
    ],
  },
  {
    section: "Quản lý học tập",
    items: [
      {
        key: "student",
        label: "Sinh viên",
        icon: Icon.personBadge,
        path: "/students",
        roles: ["admin", "secretary"],
        permission: { action: "read", resource: "student" },
      },
      {
        key: "department",
        label: "Khoa",
        icon: Icon.building,
        path: "/department",
        roles: ["admin", "secretary"],
        permission: { action: "read", resource: "department" },
      },
      {
        key: "major",
        label: "Ngành",
        icon: Icon.journal,
        path: "/major",
        roles: ["admin", "secretary"],
        permission: { action: "read", resource: "major" },
      },
      {
        key: "class",
        label: "Lớp học",
        icon: Icon.people,
        path: "/class",
        roles: ["admin", "secretary", "teacher"],
        permission: { action: "read", resource: "class" },
      },
      {
        key: "course",
        label: "Học phần",
        icon: Icon.journal,
        path: "/course",
        roles: ["admin", "secretary"],
        permission: { action: "read", resource: "course" },
      },
    ],
  },
  {
    section: "Quản trị hệ thống",
    items: [
      {
        key: "user",
        label: "Người dùng",
        icon: Icon.people,
        path: "/user",
        roles: ["admin"],
        permission: { action: "read", resource: "user" },
      },
      {
        key: "role",
        label: "Vai trò",
        icon: Icon.shieldLock,
        path: "/role",
        roles: ["admin"],
        permission: { action: "read", resource: "role" },
      },
      {
        key: "manage-templates",
        label: "Quản lý biểu mẫu",
        icon: Icon.fileText,
        path: "/admin/templates",
        roles: ["admin"],
      },
      {
        key: "audit",
        label: "Nhật ký",
        icon: Icon.clockHistory,
        path: "/audit",
        roles: ["admin"],
        permission: { action: "read", resource: "audit_log" },
      },
      {
        key: "setting",
        label: "Cài đặt",
        icon: Icon.gear,
        path: "/setting",
        roles: ["admin"],
        permission: { action: "read", resource: "setting" },
      },
    ],
  },
  {
    section: "Báo cáo",
    items: [
      {
        key: "report",
        label: "Báo cáo",
        icon: Icon.barChart,
        path: "/report",
        roles: ["admin", "secretary", "teacher"],
        permission: { action: "read", resource: "report" },
      },
      {
        key: "statistic",
        label: "Thống kê",
        icon: Icon.pieChart,
        path: "/statistic",
        roles: ["admin", "secretary"],
        permission: { action: "read", resource: "statistic" },
      },
    ],
  },
];

// ---------- Utility ----------
export function getMenuItemsForRole(role: Role): MenuItem[] {
  return MENU_ITEMS.filter((item) => {
    if (item.roles && !item.roles.includes(role)) return false;
    return true;
  });
}

export function getMenuSectionsForRole(role: Role): MenuSection[] {
  return MENU_SECTIONS.map((section) => ({
    ...section,
    items: section.items.filter((item) => {
      if (item.roles && !item.roles.includes(role)) return false;
      return true;
    }),
  })).filter((section) => section.items.length > 0);
}
