import type { ThesisTopic, TopicStatus } from "../types";

export const mockTopics: ThesisTopic[] = [
  {
    id: "1",
    code: "CNTT-2024-001",
    name: "Ứng dụng AI trong y tế",
    field: "Trí tuệ nhân tạo",
    department: "CNTT",
    lecturer: "TS. Nguyễn Văn A",
    lecturerId: "GV001",
    maxStudents: 3,
    registeredStudents: ["SV001", "SV002"],
    description: "Nghiên cứu và ứng dụng AI trong chẩn đoán bệnh",
    semester: "HK1-2024",
    status: "approved" as TopicStatus,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
  },
  {
    id: "2",
    code: "KTMT-2024-002",
    name: "Hệ thống IoT cho nông nghiệp thông minh",
    field: "IoT",
    department: "KTMT",
    lecturer: "ThS. Trần Thị B",
    lecturerId: "GV002",
    maxStudents: 2,
    registeredStudents: ["SV003"],
    description: "Xây dựng hệ thống IoT giám sát cây trồng",
    semester: "HK1-2024",
    status: "approved" as TopicStatus,
    createdAt: "2024-01-16",
    updatedAt: "2024-01-21",
  },
  {
    id: "3",
    code: "KHMT-2024-003",
    name: "Blockchain trong quản lý chuỗi cung ứng",
    field: "Blockchain",
    department: "KHMT",
    lecturer: "PGS. Lê Văn C",
    lecturerId: "GV003",
    maxStudents: 4,
    registeredStudents: ["SV004", "SV005", "SV006", "SV007"],
    description: "Ứng dụng blockchain trong quản lý logistics",
    semester: "HK1-2024",
    status: "full" as TopicStatus,
    createdAt: "2024-01-17",
    updatedAt: "2024-01-22",
  },
  {
    id: "4",
    code: "KHMT-2024-004",
    name: "Xử lý ngôn ngữ tự nhiên cho tiếng Việt",
    field: "NLP",
    department: "KHMT",
    lecturer: "TS. Phạm Thị D",
    lecturerId: "GV004",
    maxStudents: 2,
    registeredStudents: [],
    description: "Nghiên cứu NLP cho tiếng Việt",
    semester: "HK1-2024",
    status: "approved" as TopicStatus,
    createdAt: "2024-01-18",
    updatedAt: "2024-01-23",
  },
  {
    id: "5",
    code: "ATTT-2024-005",
    name: "Bảo mật mạng không dây 5G",
    field: "An toàn thông tin",
    department: "ATTT",
    lecturer: "GS. Hoàng Văn E",
    lecturerId: "GV005",
    maxStudents: 3,
    registeredStudents: ["SV008"],
    description: "Nghiên cứu bảo mật mạng 5G",
    semester: "HK1-2024",
    status: "approved" as TopicStatus,
    createdAt: "2024-01-19",
    updatedAt: "2024-01-24",
  },
  {
    id: "6",
    code: "CNTT-2024-006",
    name: "Ứng dụng AR/VR trong giáo dục",
    field: "Thực tế ảo",
    department: "CNTT",
    lecturer: "TS. Đặng Thị F",
    lecturerId: "GV006",
    maxStudents: 2,
    registeredStudents: ["SV009", "SV010"],
    description: "Xây dựng ứng dụng AR/VR hỗ trợ giảng dạy",
    semester: "HK1-2024",
    status: "approved" as TopicStatus,
    createdAt: "2024-01-20",
    updatedAt: "2024-01-25",
  },
];
