// ============================================================
// MOCK DATA: Weekly Reports - Báo cáo tuần
// ============================================================
import type {
  WeeklyReport,
  WeeklyReportStatus,
} from "../types";

export const mockWeeklyReports: WeeklyReport[] = [
  // Báo cáo tuần của SV Nguyễn Văn A (reg-001)
  {
    id: "wr-001",
    registrationId: "reg-001",
    studentId: "sv-001",
    studentName: "Nguyễn Văn A",
    weekNumber: 1,
    year: 2024,
    semester: "2023-2024-HK2",
    completedWork: "Tìm hiểu yêu cầu đề tài, nghiên cứu tài liệu về AI trong y tế",
    obstacles: "Cần thu thập thêm dữ liệu từ các nguồn uy tín",
    nextWeekPlan: "Bắt đầu thu thập và tiền xử lý dữ liệu",
    selfProgress: 15,
    attachments: ["research_notes.pdf"],
    status: "approved",
    supervisorFeedback: "Tiến độ tốt, cần tập trung vào chất lượng dữ liệu",
    progressScore: 8,
    feedbackAt: "2024-03-04",
    version: 1,
    submittedAt: "2024-03-02",
    createdAt: "2024-03-02",
    updatedAt: "2024-03-04",
  },
  {
    id: "wr-002",
    registrationId: "reg-001",
    studentId: "sv-001",
    studentName: "Nguyễn Văn A",
    weekNumber: 2,
    year: 2024,
    semester: "2023-2024-HK2",
    completedWork: "Thu thập 500 ảnh X-quang từ bệnh viện, bắt đầu tiền xử lý",
    obstacles: "Dữ liệu từ nhiều nguồn có format khác nhau",
    nextWeekPlan: "Hoàn thành tiền xử lý và bắt đầu xây dựng model baseline",
    selfProgress: 30,
    status: "approved",
    supervisorFeedback: "Khối lượng công việc tốt. Cần chú ý đến data augmentation",
    progressScore: 8.5,
    feedbackAt: "2024-03-11",
    version: 1,
    submittedAt: "2024-03-09",
    createdAt: "2024-03-09",
    updatedAt: "2024-03-11",
  },
  {
    id: "wr-003",
    registrationId: "reg-001",
    studentId: "sv-001",
    studentName: "Nguyễn Văn A",
    weekNumber: 3,
    year: 2024,
    semester: "2023-2024-HK2",
    completedWork: "Hoàn thành tiền xử lý ảnh, xây dựng model CNN baseline với accuracy 75%",
    obstacles: "Model còn overfitting, cần điều chỉnh hyperparameters",
    nextWeekPlan: "Tối ưu model, áp dụng các kỹ thuật regularization",
    selfProgress: 50,
    attachments: ["model_v0.1.ipynb"],
    status: "revision",
    supervisorFeedback: "Cần cải thiện độ chính xác lên trên 85%. Tham khảo thêm các paper gần đây.",
    version: 1,
    submittedAt: "2024-03-16",
    createdAt: "2024-03-16",
    updatedAt: "2024-03-18",
  },
  {
    id: "wr-004",
    registrationId: "reg-001",
    studentId: "sv-001",
    studentName: "Nguyễn Văn A",
    weekNumber: 4,
    year: 2024,
    semester: "2023-2024-HK2",
    completedWork: "Áp dụng transfer learning với ResNet50, accuracy đạt 87%",
    obstacles: "Thời gian training còn dài",
    nextWeekPlan: "Tối ưu inference time và viết báo cáo",
    selfProgress: 70,
    attachments: ["model_v0.2.ipynb", "results.xlsx"],
    status: "waiting_feedback",
    version: 1,
    submittedAt: "2024-03-23",
    createdAt: "2024-03-23",
    updatedAt: "2024-03-23",
  },
  // Báo cáo tuần của SV Trần Thị B (reg-002) - đã hoàn thành
  {
    id: "wr-005",
    registrationId: "reg-002",
    studentId: "sv-002",
    studentName: "Trần Thị B",
    weekNumber: 1,
    year: 2024,
    semester: "2023-2024-HK2",
    completedWork: "Hoàn thành đề cương và setup môi trường phát triển",
    obstacles: "Không có",
    nextWeekPlan: "Thiết kế database và API",
    selfProgress: 20,
    status: "approved",
    supervisorFeedback: "Đề cương tốt, có thể tiến hành thiết kế",
    progressScore: 9,
    feedbackAt: "2024-02-05",
    version: 1,
    submittedAt: "2024-02-03",
    createdAt: "2024-02-03",
    updatedAt: "2024-02-05",
  },
  {
    id: "wr-006",
    registrationId: "reg-002",
    studentId: "sv-002",
    studentName: "Trần Thị B",
    weekNumber: 2,
    year: 2024,
    semester: "2023-2024-HK2",
    completedWork: "Thiết kế database schema, tạo các bảng chính",
    obstacles: "Cần tối ưu relationships giữa các bảng",
    nextWeekPlan: "Implement API endpoints cơ bản",
    selfProgress: 40,
    status: "approved",
    supervisorFeedback: "Schema tốt, chú ý indexing cho performance",
    progressScore: 8.5,
    feedbackAt: "2024-02-12",
    version: 1,
    submittedAt: "2024-02-10",
    createdAt: "2024-02-10",
    updatedAt: "2024-02-12",
  },
];

export const getWeeklyReportStatusColor = (
  status: WeeklyReportStatus
): "default" | "warning" | "info" | "success" | "error" => {
  const colors: Record<WeeklyReportStatus, "default" | "warning" | "info" | "success" | "error"> = {
    draft: "default",
    submitted: "info",
    waiting_feedback: "warning",
    approved: "success",
    revision: "error",
  };
  return colors[status];
};

export const getWeekLabel = (weekNumber: number, semester: string): string => {
  const [yearPart, termPart] = semester.split("-");
  return `HK${termPart.replace("HK", "")} - Tuần ${weekNumber}`;
};
