export {
  isBrowser,
  isServer,
  isDevelopment,
  isProduction,
  isTest,
  getEnvironment,
  isNextJS,
  isReact,
} from "./env.utils";
// format
export type { DateFormatLocale } from "./format.utils";
export {
  formatDateLocale,
  formatDateTime,
  formatDateCustom,
  timeAgoVN,
  timeAgoShort,
  smartDate,
  getDayOfWeekVN,
  getDayOfWeekShortVN,
  formatDurationBetween,
  formatDurationShort,
  truncateString,
  truncateByWords,
  capitalizeWords,
  capitalize,
  slugify,
  unslugify,
  normalizeWhitespace,
  removeWhitespace,
  escapeTemplate,
  escapeHtml,
  unescapeHtml,
  padStart,
  padEnd,
  repeat,
  abbreviateName,
  parseName,
  formatNameLastFirst,
  maskPhone,
  maskEmail,
  maskNumber,
  maskAddress,
  ordinal,
  ordinalVN,
  camelToKebab,
  camelToSnake,
  kebabOrSnakeToCamel,
  kebabOrSnakeToPascal,
  formatBytes,
  toRoman,
  fromRoman,
  getInitials,
  sanitizeFilename,
  formatVersion,
  camelToTitle,
} from "./format.utils";
// validation
export {
  isValidEmail,
  validateEmail,
  isValidPhoneVN,
  isValidPhoneInternational,
  validatePhone,
  formatPhoneVN,
  validatePassword,
  getPasswordStrength,
  isPasswordContainingUserInfo,
  isValidUrl,
  isValidUrlWithProtocol,
  validateUrl,
  validateUsername,
  isReservedUsername,
  validateName,
  isValidCCCD,
  isValidTaxId,
  isPositiveInteger,
  isInRange,
  isValidDecimal,
  hasValidExtension as validateHasValidExtension,
  isValidMimeType,
  isValidFileSize as validateIsValidFileSize,
  validateField,
  validateForm,
  required,
  minLength,
  maxLength,
  pattern,
  isEmpty as validateIsEmpty,
  isValidJSON,
  isValidHexColor,
  isValidCreditCard,
  isValidIPv4,
  isValidIPv6,
  isLeapYear,
  isValidDateFormat,
  isValidDateRange,
} from "./validation.utils";
export type {
  PasswordValidationResult,
  PasswordOptions,
  UsernameValidationResult,
  ValidationRule,
  ValidationSchema,
} from "./validation.utils";

// regex
export { regexPatterns } from "./regex.utils";

// strorage
export {
  isStorageAvailable,
  getItem,
  setItem,
  removeItem,
  clear,
  getAllKeys,
  hasKey,
  getStorageSize,
  setWithExpiry,
  getWithExpiry,
  setWithExpiryDate,
  getTimeRemaining,
  getOrSet,
  getOrSetWithExpiry,
  updateItem,
  mergeItem,
  setMultiple,
  getMultiple,
  removeMultiple,
  clearByPrefix,
  safeJsonParse,
  safeJsonStringify,
  setWithTTL,
  getWithTTL,
  createNamespaceStorage,
  addStorageListener,
  broadcastStorageChange,
} from "./storage.utils";
export type {
  StorageType,
  StorageItem,
  NamespacedStorage,
} from "./storage.utils";

// array
export {
  createArray,
  padArray,
  chunk,
  chunkEqual,
  split,
  duplicates,
  duplicatesBy,
  frequencies,
  frequenciesBy,
  move,
  moveUp,
  moveDown,
  rotate,
  sortByMultiple,
  groupCount,
  filterNullish,
  trimBy,
  toggle,
  replace,
  upsert,
  firstOr,
  lastOr,
  at,
  includesAll,
  includesAny,
  arraysEqual,
  arraysEqualWith,
  sum,
  sumBy,
  average,
  averageBy,
  min,
  max,
  median,
  mode,
  window,
  windowStep,
  zip,
  zipWith,
  zipObject,
  scan,
} from "./array.uitls";
export type { Primitive, DeepPartial } from "./array.uitls";

// object
export {
  clone,
  deepClone,
  deepCloneExtended,
  pick,
  pickBy,
  omit,
  omitBy,
  get,
  set,
  del,
  has,
  merge,
  deepMerge,
  mergeArrays,
  toEntries,
  toKeys,
  toValues,
  mapKeys,
  mapValues,
  invert as objectInvert,
  isEqual,
  isDeepEqual,
  isEmpty as isObjectEmpty,
  isNotEmpty as isObjectNotEmpty,
  flatten as flattenObject,
  unflatten,
  getPaths,
  size as objectSize,
  randomProperty,
  randomKey,
  transform,
  fromEntries,
  fromEntriesGeneric,
} from "./object.uitls";

// number
export {
  randomInt,
  randomFloat,
  clamp,
  roundFloat,
  floorFloat,
  ceilFloat,
  sign,
  percentage,
  percentageFormatted,
  fromPercentage,
  percentageChange,
  isWithinPercentage,
  formatNumber,
  shortenNumber,
  formatCurrencyVND,
  formatPhoneNumber,
  parseNumber,
  parseFormattedNumber,
  numericRange,
  divideRange,
  isInRange as isInNumberRange,
  isInOpenRange,
  gcd,
  lcm,
  gcdMultiple,
  lcmMultiple,
  factorial,
  fibonacci,
  fibonacciMemo,
  distance,
  angle,
  toRadians,
  toDegrees,
  isApproximatelyEqual,
  compareWithPrecision,
  isInteger,
  isFloat,
  isPositive,
  isNegative,
  isEven,
  isOdd,
  isSafeInteger,
  isFiniteNumber,
  isNaNValue,
  mean,
  standardDeviation,
  variance,
} from "./number.utils";

// date
export {
  formatDate,
  formatDateRelative,
  timeAgo,
  toDate,
  toTimestamp,
  toISOString,
  toUnixTimestamp,
  isToday,
  isYesterday,
  isTomorrow,
  isSameDay,
  isSameWeek,
  isSameMonth,
  isSameYear,
  isBefore,
  isAfter,
  isEqual as isDateEqual,
  getDaysBetween,
  getHoursBetween,
  getMinutesBetween,
  getTimeDiff,
  addDays,
  addMonths,
  addYears,
  subtractDays,
  subtractMonths,
  subtractYears,
  startOfDay,
  endOfDay,
  startOfWeek,
  endOfWeek,
  startOfMonth,
  endOfMonth,
  startOfYear,
  endOfYear,
  getDaysInMonth,
  getWeekNumber,
  getQuarter,
  getDayOfWeek,
  getMoonPhase,
  isInRange as isInDateRange,
  isInCurrentWeek,
  isWeekday,
  isWeekend,
  getBusinessDaysBetween,
  parseDate,
  parseISODate,
  parseUnixTimestamp,
  parseUnixTimestampMs,
  getMonthName,
  getMonthShortName,
  getDayName,
  getDayShortName,
  getDatesInMonth,
  getDatesInWeek,
  getWeekRange,
  getMonthRange,
} from "./date.utils";
export type { DateFormat, TimeAgoUnit, TimeAgoOptions } from "./date.utils";

// async
export { sleep } from "./async.utils";
export type {
  RetryOptions,
  PollOptions,
  QueueOptions,
  WaitForOptions,
} from "./async.utils";

// browser
export {
  getUrlParam,
  getUrlParamsAsObject,
  buildUrl,
  updateUrlParams,
  scrollToTop,
  scrollToElement,
  scrollToBottom,
  isScrolledToBottom,
  getCookie,
  setCookie,
  deleteCookie,
  isOnline,
  getCurrentHash,
  reloadPage,
  isTabActive,
  isWindowFocused,
  getTimezone,
} from "./browser.utils";
export type {
  CopyToClipboardOptions,
  CopyToClipboardResult,
  CookieOptions,
} from "./browser.utils";

// ============================================
// URL
// ============================================
export {
  parseUrl,
  buildUrl as urlBuildUrl,
  getDomain,
  getSubdomain,
  getRootDomain,
  getProtocol,
  getPort,
  getPathSegments,
  getLastPathSegment,
  isAbsoluteUrl,
  isRelativeUrl,
  joinUrl,
  normalizeUrl,
  addParam,
  setParam,
  removeParam,
  getParam,
  hasParam,
  getParams,
  buildQueryString,
  parseQueryString,
  getHash,
  getCurrentUrl,
  getCurrentOrigin,
  navigate,
  replaceUrl,
  openInNewTab,
  encodeUrl,
  decodeUrl,
  encodeFullUrl,
  decodeFullUrl,
  isUrlSecure,
  getExtension,
  getFilename,
  urlMatches,
  createMailtoUrl,
  createTelUrl,
  createSmsUrl,
} from "./url.utils";
export type { ParsedUrl } from "./url.utils";

// CRYPTO
export { base64Encode, base64Decode, randomString, uuid } from "./crypto.utils";

// file
export {
  formatFileSize,
  parseFileSize,
  isValidFileSize,
  getMimeType,
  isImage,
  isVideo,
  isAudio,
  isPdf,
  isDocument,
  isArchive,
  getFileExtension,
  getFileNameWithoutExtension,
  hasValidExtension,
  getFileIconType,
  fileToBase64,
  fileToBase64Data,
  base64ToBlob,
  base64ToFile,
  readFileAsText,
  readFileAsArrayBuffer,
  getImageDimensions,
  downloadBlob,
  downloadUrl,
  downloadText,
  downloadBase64,
  downloadJson,
  validateFile,
  createFileInput,
  compressImage,
  resizeImage,
  getFileIcon,
  getFileColor,
} from "./file.utils";
export type { UploadOptions, FileValidationResult } from "./file.utils";

// dom
export {
  isElementInViewport,
  isElementVisible,
  isElementEnabled,
  getElementPosition,
  getElementPositionRelativeToDocument,
  getElementCenter,
  getDimensions,
  getScrollbarWidth,
  scrollIntoViewWithOffset,
  scrollElementToTop,
  on,
  once,
  delegate,
  fadeIn,
  fadeOut,
  slideIn,
  slideOut,
  isInDOM,
  waitForElementInDOM,
  getFocusableElements,
  moveFocus,
  selectText,
} from "./dom.utils";
