import type { TemplateItem } from "../types";

export { TemplateItem };

export const mockTemplates: TemplateItem[] = [
  // === GIAI ĐOẠN 1: CHUẨN BỊ ===
  {
    id: 1,
    code: "NIIE-KLTN-01",
    name: "Danh sách đề tài",
    nameEn: "Thesis Topic List",
    description: "Danh sách các đề tài khóa luận tốt nghiệp theo từng kỳ",
    icon: "folder",
    color: "#1890ff",
    category: "admin",
    stage: "preparation",
    fileType: "docx",
    forRoles: ["admin", "secretary"],
    isActive: true,
  },
  {
    id: 8,
    code: "NIIE-KLTN-08",
    name: "Mẫu viết báo cáo",
    nameEn: "Thesis Report Template",
    description: "Mẫu định dạng chuẩn để viết báo cáo khóa luận tốt nghiệp",
    icon: "edit",
    color: "#2f54d2",
    category: "student",
    stage: "preparation",
    fileType: "docx",
    forRoles: ["student", "teacher"],
    isActive: true,
  },

  // === GIAI ĐOẠN 2: GIAO ĐỀ TÀI ===
  {
    id: 2,
    code: "NIIE-KLTN-02",
    name: "Phân công đề tài khóa luận",
    nameEn: "Thesis Assignment Form",
    description: "Quyết định phân công đề tài cho sinh viên (19/02/2024 - 27/05/2024)",
    icon: "team",
    color: "#52c41a",
    category: "admin",
    stage: "assignment",
    fileType: "docx",
    forRoles: ["admin", "secretary"],
    isActive: true,
  },
  {
    id: 3,
    code: "NIIE-KLTN-03",
    name: "Quyết định giao đề tài",
    nameEn: "Thesis Assignment Decision",
    description: "Quyết định chính thức giao đề tài khóa luận tốt nghiệp cho sinh viên",
    icon: "check",
    color: "#faad14",
    category: "admin",
    stage: "assignment",
    fileType: "docx",
    forRoles: ["admin", "secretary"],
    isActive: true,
  },

  // === GIAI ĐOẠN 3: THỰC HIỆN ===
  {
    id: 4,
    code: "NIIE-KLTN-04",
    name: "Báo cáo tiến độ",
    nameEn: "Progress Report Template",
    description: "Mẫu báo cáo tiến độ hàng tuần/tháng cho sinh viên theo đề tài",
    icon: "calendar",
    color: "#722ed1",
    category: "student",
    stage: "execution",
    fileType: "doc",
    forRoles: ["student", "teacher"],
    isActive: true,
  },
  {
    id: 5,
    code: "NIIE-KLTN-05",
    name: "Xin đổi đề tài/GVHD",
    nameEn: "Topic/Supervisor Change Request",
    description: "Đơn xin thay đổi đề tài hoặc giảng viên hướng dẫn",
    icon: "swap",
    color: "#eb2f96",
    category: "student",
    stage: "execution",
    fileType: "docx",
    forRoles: ["student", "teacher", "admin"],
    isActive: true,
  },
  {
    id: 6,
    code: "NIIE-KLTN-06",
    name: "Gia hạn báo cáo (SV)",
    nameEn: "Report Extension Request (Student)",
    description: "Đơn xin gia hạn thời gian nộp báo cáo - dành cho sinh viên",
    icon: "clock",
    color: "#fa8c16",
    category: "student",
    stage: "execution",
    fileType: "docx",
    forRoles: ["student", "teacher"],
    isActive: true,
  },
  {
    id: 7,
    code: "NIIE-KLTN-07",
    name: "Gia hạn báo cáo (GV)",
    nameEn: "Report Extension Approval (Supervisor)",
    description: "Mẫu đề nghị gia hạn từ giảng viên hướng dẫn",
    icon: "clock",
    color: "#13c2c2",
    category: "teacher",
    stage: "execution",
    fileType: "docx",
    forRoles: ["teacher", "admin"],
    isActive: true,
  },
  {
    id: 9,
    code: "NIIE-KLTN-09",
    name: "Điều chỉnh thông tin KL",
    nameEn: "Thesis Info Adjustment Form",
    description: "Mẫu điều chỉnh thông tin khóa luận (tên đề tài, mô tả, yêu cầu)",
    icon: "file",
    color: "#a0d911",
    category: "student",
    stage: "execution",
    fileType: "docx",
    forRoles: ["student", "teacher"],
    isActive: true,
  },

  // === GIAI ĐOẠN 4: ĐÁNH GIÁ ===
  {
    id: 10,
    code: "NIIE-KLTN-10",
    name: "Đánh giá KL (GVHD)",
    nameEn: "Supervisor Evaluation Form",
    description: "Phiếu đánh giá khóa luận dành cho giảng viên hướng dẫn",
    icon: "solution",
    color: "#52c41a",
    category: "teacher",
    stage: "evaluation",
    fileType: "docx",
    forRoles: ["teacher"],
    isActive: true,
  },
  {
    id: 11,
    code: "NIIE-KLTN-11",
    name: "Đánh giá KL (GV phản biện)",
    nameEn: "Reviewer Evaluation Form",
    description: "Phiếu đánh giá khóa luận dành cho giảng viên phản biện",
    icon: "safety",
    color: "#fa541c",
    category: "teacher",
    stage: "evaluation",
    fileType: "docx",
    forRoles: ["teacher"],
    isActive: true,
  },
  {
    id: 12,
    code: "NIIE-KLTN-12",
    name: "Đánh giá hội đồng",
    nameEn: "Council Evaluation Form",
    description: "Phiếu đánh giá của hội đồng bảo vệ khóa luận",
    icon: "team",
    color: "#722ed1",
    category: "teacher",
    stage: "evaluation",
    fileType: "docx",
    forRoles: ["teacher"],
    isActive: true,
  },
  {
    id: 13,
    code: "NIIE-KLTN-13",
    name: "Tổng hợp đánh giá HĐ",
    nameEn: "Council Evaluation Summary",
    description: "Bảng tổng hợp điểm đánh giá của hội đồng bảo vệ",
    icon: "trophy",
    color: "#faad14",
    category: "admin",
    stage: "evaluation",
    fileType: "docx",
    forRoles: ["admin", "secretary"],
    isActive: true,
  },
];
